const mongoose = require('mongoose');
require('dotenv').config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/civic_voice';

const stories = [
  // ============ SCHOLARSHIP STORIES (5) ============
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Priya",
    heroNameHi: "प्रिया",
    heroNameMr: "प्रिया",
    heroAge: 19,
    heroGender: "female",
    heroOccupation: "student",
    heroOccupationHi: "छात्रा",
    heroOccupationMr: "विद्यार्थिनी",
    village: "Satara",
    villageHi: "सातारा",
    villageMr: "सातारा",
    district: "Satara",
    category: "scholarship",
    problem: "Her father is a farmer with small land. She got admission in college but couldn't afford the fees of ₹25,000 per year.",
    problemHi: "उनके पिता छोटे किसान हैं। उन्हें कॉलेज में दाखिला मिला लेकिन ₹25,000 प्रति वर्ष की फीस नहीं भर सकती थीं।",
    problemMr: "तिचे वडील छोटे शेतकरी आहेत. तिला महाविद्यालयात प्रवेश मिळाला पण दरवर्षी ₹25,000 फी भरता येत नव्हती.",
    action: "She applied for the Post-Matric Scholarship scheme. Her father got help from the village sarpanch to fill the form.",
    actionHi: "उन्होंने पोस्ट-मैट्रिक छात्रवृत्ति योजना के लिए आवेदन किया। फॉर्म भरने में गाँव के सरपंच ने मदद की।",
    actionMr: "तिने पोस्ट-मॅट्रिक शिष्यवृत्ती योजनेसाठी अर्ज केला. फॉर्म भरण्यासाठी गावच्या सरपंचांनी मदत केली.",
    result: "She got full fee reimbursement of ₹25,000 and ₹5,000 for books. Now she's in second year, studying to become a teacher.",
    resultHi: "उन्हें ₹25,000 की पूरी फीस और किताबों के लिए ₹5,000 मिले। अब वह दूसरे वर्ष में हैं, शिक्षक बनने की पढ़ाई कर रही हैं।",
    resultMr: "तिला ₹25,000 ची संपूर्ण फी माफी आणि पुस्तकांसाठी ₹5,000 मिळाले. आता ती दुसऱ्या वर्षात आहे, शिक्षिका होण्यासाठी शिकत आहे.",
    message: "Don't let money stop your dreams. This scheme exists for students like us.",
    messageHi: "पैसों को अपने सपनों के आड़े न आने दें। यह योजना हम जैसे छात्रों के लिए है।",
    messageMr: "पैशांना आपल्या स्वप्नांमध्ये अडथळा येऊ देऊ नका. ही योजना आमच्यासारख्या विद्यार्थ्यांसाठी आहे.",
    tags: ["student", "woman", "youth", "scholarship"],
    language: "multilingual",
    likes: 89,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Raju",
    heroNameHi: "राजू",
    heroNameMr: "राजू",
    heroAge: 17,
    heroGender: "male",
    heroOccupation: "student",
    heroOccupationHi: "छात्र",
    heroOccupationMr: "विद्यार्थी",
    village: "Aurangabad",
    villageHi: "औरंगाबाद",
    villageMr: "औरंगाबाद",
    district: "Aurangabad",
    category: "scholarship",
    problem: "His mother is a widow and works as a laborer. He scored 85% in 12th but couldn't afford engineering college fees.",
    problemHi: "उनकी माँ विधवा हैं और मजदूरी करती हैं। उन्होंने 12वीं में 85% अंक प्राप्त किए लेकिन इंजीनियरिंग कॉलेज की फीस नहीं भर सकते थे।",
    problemMr: "त्याची आई विधवा आहे आणि मजुरी करते. त्याने 12वीत 85% गुण मिळवले पण अभियांत्रिकी महाविद्यालयाची फी भरू शकत नव्हता.",
    action: "His teacher told him about the Merit-cum-Means Scholarship. He applied online at the cyber cafe.",
    actionHi: "उनके शिक्षक ने उन्हें मेरिट-कम-मीन्स छात्रवृत्ति के बारे में बताया। उन्होंने साइबर कैफे में ऑनलाइन आवेदन किया।",
    actionMr: "त्याच्या शिक्षकाने त्याला मेरिट-कम-मीन्स शिष्यवृत्तीबद्दल सांगितले. त्याने सायबर कॅफेत ऑनलाइन अर्ज केला.",
    result: "He got ₹50,000 per year scholarship. Now he's in second year engineering and also tutors village children on weekends.",
    resultHi: "उन्हें प्रति वर्ष ₹50,000 की छात्रवृत्ति मिली। अब वह इंजीनियरिंग के दूसरे वर्ष में हैं और सप्ताहांत में गाँव के बच्चों को पढ़ाते हैं।",
    resultMr: "त्याला दर वर्षी ₹50,000 ची शिष्यवृत्ती मिळाली. आता तो अभियांत्रिकीच्या दुसऱ्या वर्षात आहे आणि शनिवार-रविवार गावातील मुलांना शिकवतो.",
    message: "Education is the only wealth that cannot be stolen. This scholarship made me an engineer.",
    messageHi: "शिक्षा ही एकमेव संपत्ति है जिसे चुराया नहीं जा सकता। इस छात्रवृत्ति ने मुझे इंजीनियर बना दिया।",
    messageMr: "शिक्षण ही एकमेव संपत्ती आहे जी चोरता येत नाही. या शिष्यवृत्तीने मला अभियंता बनवले.",
    tags: ["student", "male", "youth", "scholarship", "merit"],
    language: "multilingual",
    likes: 76,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Laxmi",
    heroNameHi: "लक्ष्मी",
    heroNameMr: "लक्ष्मी",
    heroAge: 20,
    heroGender: "female",
    heroOccupation: "college student",
    heroOccupationHi: "कॉलेज छात्रा",
    heroOccupationMr: "महाविद्यालयीन विद्यार्थिनी",
    village: "Nanded",
    villageHi: "नांदेड़",
    villageMr: "नांदेड",
    district: "Nanded",
    category: "scholarship",
    problem: "She belongs to a tribal community. Her parents couldn't afford her nursing course fees of ₹40,000.",
    problemHi: "वह आदिवासी समुदाय से हैं। उनके माता-पिता ₹40,000 की नर्सिंग कोर्स फीस नहीं भर सकते थे।",
    problemMr: "ती आदिवासी समुदायातील आहे. तिचे पालक ₹40,000 ची नर्सिंग कोर्स फी भरू शकत नव्हते.",
    action: "She applied for the Tribal Development Department Scholarship. The Anganwadi worker helped her fill the form.",
    actionHi: "उन्होंने आदिवासी विकास विभाग छात्रवृत्ति के लिए आवेदन किया। आंगनवाड़ी कार्यकर्ता ने फॉर्म भरने में मदद की।",
    actionMr: "तिने आदिवासी विकास विभाग शिष्यवृत्तीसाठी अर्ज केला. अंगणवाडी सेविकेने फॉर्म भरण्यास मदत केली.",
    result: "She got 100% fee waiver and ₹10,000 for hostel expenses. Now she's a trained nurse serving her community.",
    resultHi: "उन्हें 100% फीस माफी और हॉस्टल खर्च के लिए ₹10,000 मिले। अब वह प्रशिक्षित नर्स हैं और अपने समुदाय की सेवा कर रही हैं।",
    resultMr: "तिला 100% फी माफी आणि हॉस्टल खर्चासाठी ₹10,000 मिळाले. आता ती प्रशिक्षित परिचारिका आहे आणि तिच्या समुदायाची सेवा करते आहे.",
    message: "I always wanted to help people. This scholarship helped me become a nurse.",
    messageHi: "मैं हमेशा लोगों की मदद करना चाहती थी। इस छात्रवृत्ति ने मुझे नर्स बनने में मदद की।",
    messageMr: "मला नेहमी लोकांची मदत करायची होती. या शिष्यवृत्तीने मला परिचारिका बनण्यास मदत केली.",
    tags: ["student", "woman", "tribal", "scholarship", "nursing"],
    language: "multilingual",
    likes: 82,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Suresh",
    heroNameHi: "सुरेश",
    heroNameMr: "सुरेश",
    heroAge: 16,
    heroGender: "male",
    heroOccupation: "school student",
    heroOccupationHi: "स्कूल छात्र",
    heroOccupationMr: "शाळेतील विद्यार्थी",
    village: "Jalna",
    villageHi: "जालना",
    villageMr: "जालना",
    district: "Jalna",
    category: "scholarship",
    problem: "He lost his father at age 10. His mother works as a domestic help. He wanted to study but couldn't afford school fees.",
    problemHi: "10 साल की उम्र में पिता खो दिए। माँ घरेलू सहायिका हैं। पढ़ना चाहते थे लेकिन स्कूल फीस नहीं भर सकते थे।",
    problemMr: "वय 10 व्या वर्षी वडील गमावले. आई घरकाम करते. शिकायचे होते पण शाळेची फी भरू शकत नव्हता.",
    action: "His teacher enrolled him in the National Means-cum-Merit Scholarship scheme. He got ₹6,000 per year.",
    actionHi: "उनके शिक्षक ने उन्हें राष्ट्रीय मीन्स-कम-मेरिट छात्रवृत्ति योजना में दाखिला दिलाया। उन्हें प्रति वर्ष ₹6,000 मिले।",
    actionMr: "त्याच्या शिक्षकाने त्याला राष्ट्रीय मीन्स-कम-मेरिट शिष्यवृत्ती योजनेत प्रवेश दिला. त्याला दर वर्षी ₹6,000 मिळाले.",
    result: "He passed 10th with 90% and now in 11th. He wants to become a doctor and serve his village.",
    resultHi: "उन्होंने 10वीं 90% अंकों के साथ पास की और अब 11वीं में हैं। वह डॉक्टर बनकर अपने गाँव की सेवा करना चाहते हैं।",
    resultMr: "त्याने 10वी 90% गुणांनी पास केली आणि आता 11वीत आहे. त्याला डॉक्टर होऊन आपल्या गावाची सेवा करायची आहे.",
    message: "Poverty is not a barrier if you have determination. This scholarship kept my dream alive.",
    messageHi: "गरीबी बाधा नहीं है अगर आपमें दृढ़ संकल्प है। इस छात्रवृत्ति ने मेरे सपने को जिंदा रखा।",
    messageMr: "तुमच्यात दृढनिश्चय असेल तर गरिबी अडथळा नाही. या शिष्यवृत्तीने माझे स्वप्न जिवंत ठेवले.",
    tags: ["student", "male", "youth", "scholarship", "orphan"],
    language: "multilingual",
    likes: 94,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Kavita",
    heroNameHi: "कविता",
    heroNameMr: "कविता",
    heroAge: 22,
    heroGender: "female",
    heroOccupation: "post-graduate student",
    heroOccupationHi: "स्नातकोत्तर छात्रा",
    heroOccupationMr: "पदव्युत्तर विद्यार्थिनी",
    village: "Latur",
    villageHi: "लातूर",
    villageMr: "लातूर",
    district: "Latur",
    category: "scholarship",
    problem: "She wants to pursue MA in Social Work but family has no money for fees. Father is a marginal farmer.",
    problemHi: "वह एमए सोशल वर्क करना चाहती हैं लेकिन परिवार के पास फीस के लिए पैसे नहीं हैं। पिता सीमांत किसान हैं।",
    problemMr: "तिला एमए सोशल वर्क करायचे आहे पण कुटुंबाकडे फी साठी पैसे नाहीत. वडील सीमांत शेतकरी आहेत.",
    action: "She applied for the Rajarshi Chhatrapati Shahu Maharaj Merit Scholarship. Got ₹25,000 per year.",
    actionHi: "उन्होंने राजर्षि छत्रपति शाहू महाराज मेरिट छात्रवृत्ति के लिए आवेदन किया। प्रति वर्ष ₹25,000 मिले।",
    actionMr: "तिने राजर्षी छत्रपती शाहू महाराज मेरिट शिष्यवृत्तीसाठी अर्ज केला. दर वर्षी ₹25,000 मिळाले.",
    result: "Now in final year MA, working on a project about rural women empowerment. Plans to start an NGO.",
    resultHi: "अब एमए के अंतिम वर्ष में हैं, ग्रामीण महिला सशक्तिकरण पर प्रोजेक्ट कर रही हैं। एनजीओ शुरू करने की योजना है।",
    resultMr: "आता एमएच्या अंतिम वर्षात आहे, ग्रामीण महिला सक्षमीकरणावर प्रकल्प करते आहे. एनजीओ सुरू करण्याची योजना आहे.",
    message: "Education gives you power to change not just your life, but your entire community.",
    messageHi: "शिक्षा आपको सिर्फ अपनी नहीं, बल्कि पूरे समुदाय की जिंदगी बदलने की ताकत देती है।",
    messageMr: "शिक्षण तुम्हाला फक्त तुमचेच नव्हे तर संपूर्ण समुदायाचे आयुष्य बदलण्याची शक्ती देते.",
    tags: ["student", "woman", "youth", "scholarship", "postgraduate"],
    language: "multilingual",
    likes: 71,
    usedCount: 0,
    isActive: true
  },

  // ============ HEALTH STORIES (5) ============
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Ramabai",
    heroNameHi: "रमाबाई",
    heroNameMr: "रमाबाई",
    heroAge: 62,
    heroGender: "female",
    heroOccupation: "retired laborer",
    heroOccupationHi: "सेवानिवृत्त मजदूर",
    heroOccupationMr: "निवृत्त मजूर",
    village: "Osmanabad",
    villageHi: "उस्मानाबाद",
    villageMr: "उस्मानाबाद",
    district: "Osmanabad",
    category: "health",
    problem: "She had a heart condition and needed surgery costing ₹2 lakh. Her sons are daily wagers and couldn't afford it.",
    problemHi: "उन्हें दिल की बीमारी थी और ₹2 लाख की सर्जरी की जरूरत थी। उनके बेटे दिहाड़ी मजदूर हैं और इसे वहन नहीं कर सकते थे।",
    problemMr: "तिला हृदयविकार होता आणि ₹2 लाखाच्या शस्त्रक्रियेची गरज होती. तिचे मुलगे रोजंदारीवर काम करतात आणि ते परवडत नव्हते.",
    action: "A social worker told her about the Pradhan Mantri Jan Arogya Yojana (Ayushman Bharat). She got a golden card.",
    actionHi: "एक समाजसेविका ने उन्हें प्रधानमंत्री जन आरोग्य योजना (आयुष्मान भारत) के बारे में बताया। उन्हें गोल्डन कार्ड मिला।",
    actionMr: "एका समाजसेविकेने तिला प्रधानमंत्री जन आरोग्य योजना (आयुष्मान भारत) बद्दल सांगितले. तिला गोल्डन कार्ड मिळाले.",
    result: "Her entire surgery was covered under the scheme. She's now healthy and takes care of her grandchildren.",
    resultHi: "उनकी पूरी सर्जरी योजना के तहत कवर हो गई। अब वह स्वस्थ हैं और अपने पोते-पोतियों की देखभाल करती हैं।",
    resultMr: "तिची संपूर्ण शस्त्रक्रिया योजनेअंतर्गत झाली. आता ती निरोगी आहे आणि तिच्या नातवंडांची काळजी घेते.",
    message: "Ayushman Bharat gave me a second chance at life. I thought I would die, but now I'm alive.",
    messageHi: "आयुष्मान भारत ने मुझे जीवन का दूसरा मौका दिया। मुझे लगा था कि मैं मर जाऊंगी, लेकिन अब मैं जीवित हूं।",
    messageMr: "आयुष्मान भारतने मला जीवनाची दुसरी संधी दिली. मला वाटले होते की मी मरेन, पण आता मी जिवंत आहे.",
    tags: ["health", "senior", "woman", "ayushman", "surgery"],
    language: "multilingual",
    likes: 112,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Sitaram",
    heroNameHi: "सीताराम",
    heroNameMr: "सीताराम",
    heroAge: 45,
    heroGender: "male",
    heroOccupation: "farmer",
    heroOccupationHi: "किसान",
    heroOccupationMr: "शेतकरी",
    village: "Beed",
    villageHi: "बीड",
    villageMr: "बीड",
    district: "Beed",
    category: "health",
    problem: "He was diagnosed with kidney stones and needed surgery. As a small farmer, he had no savings for medical expenses.",
    problemHi: "उन्हें किडनी में पथरी का पता चला और सर्जरी की जरूरत थी। छोटे किसान होने के कारण, उनके पास चिकित्सा खर्च के लिए बचत नहीं थी।",
    problemMr: "त्याला किडनीत दगड असल्याचे निदान झाले आणि शस्त्रक्रियेची गरज होती. छोटे शेतकरी असल्याने, त्याच्याकडे वैद्यकीय खर्चासाठी बचत नव्हती.",
    action: "He registered for the Mahatma Phule Jan Arogya Yojana at the district hospital. Got a health card.",
    actionHi: "उन्होंने जिला अस्पताल में महात्मा फुले जन आरोग्य योजना के लिए पंजीकरण कराया। हेल्थ कार्ड मिला।",
    actionMr: "त्याने जिल्हा रुग्णालयात महात्मा फुले जन आरोग्य योजनेसाठी नोंदणी केली. हेल्थ कार्ड मिळाले.",
    result: "Free surgery worth ₹80,000 was done. He's back to farming and even bought a buffalo from the money he saved.",
    resultHi: "₹80,000 की मुफ्त सर्जरी हुई। वह वापस खेती कर रहे हैं और बचाए गए पैसों से एक भैंस भी खरीदी।",
    resultMr: "₹80,000 ची मोफत शस्त्रक्रिया झाली. तो पुन्हा शेती करतो आहे आणि वाचवलेल्या पैशांतून एक म्हैसही विकत घेतली.",
    message: "I was worried I'd have to sell my land for treatment. This scheme saved my land and my life.",
    messageHi: "मैं चिंतित था कि इलाज के लिए अपनी जमीन बेचनी पड़ेगी। इस योजना ने मेरी जमीन और मेरी जान बचाई।",
    messageMr: "मी काळजीत होतो की उपचारासाठी माझी जमीन विकावी लागेल. या योजनेने माझी जमीन आणि माझे प्राण वाचवले.",
    tags: ["health", "farmer", "male", "surgery", "insurance"],
    language: "multilingual",
    likes: 87,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Sunita",
    heroNameHi: "सुनीता",
    heroNameMr: "सुनीता",
    heroAge: 28,
    heroGender: "female",
    heroOccupation: "pregnant woman",
    heroOccupationHi: "गर्भवती महिला",
    heroOccupationMr: "गर्भवती महिला",
    village: "Parbhani",
    villageHi: "परभणी",
    villageMr: "परभणी",
    district: "Parbhani",
    category: "health",
    problem: "She was pregnant with her first child but had severe anemia. Hospital said she needed blood transfusion and special care.",
    problemHi: "वह अपने पहले बच्चे से गर्भवती थीं लेकिन उन्हें गंभीर एनीमिया था। अस्पताल ने कहा कि उन्हें ब्लड ट्रांसफ्यूजन और विशेष देखभाल की जरूरत है।",
    problemMr: "ती तिच्या पहिल्या मुलापासून गर्भवती होती पण तिला गंभीर अशक्तपणा होता. रुग्णालयाने सांगितले की तिला रक्त संक्रमण आणि विशेष काळजीची गरज आहे.",
    action: "ASHA worker enrolled her in Janani Suraksha Yojana. She got free delivery care and financial assistance.",
    actionHi: "आशा कार्यकर्ता ने उन्हें जननी सुरक्षा योजना में नामांकित किया। उन्हें मुफ्त प्रसव देखभाल और वित्तीय सहायता मिली।",
    actionMr: "आशा कार्यकर्त्याने तिला जननी सुरक्षा योजनेत नोंदणी केली. तिला मोफत प्रसूती काळजी आणि आर्थिक मदत मिळाली.",
    result: "She delivered a healthy baby girl. Got ₹1,400 as cash assistance. Both mother and baby are healthy.",
    resultHi: "उन्होंने एक स्वस्थ बच्ची को जन्म दिया। ₹1,400 नकद सहायता मिली। मां और बच्चा दोनों स्वस्थ हैं।",
    resultMr: "तिने एक निरोगी मुलगी जन्माला घातली. ₹1,400 रोख मदत मिळाली. आई आणि बाळ दोघेही निरोगी आहेत.",
    message: "I was so scared for my baby. This scheme made sure we both survived and are healthy.",
    messageHi: "मैं अपने बच्चे के लिए बहुत डरी हुई थी। इस योजना ने सुनिश्चित किया कि हम दोनों जीवित रहें और स्वस्थ रहें।",
    messageMr: "मी माझ्या बाळासाठी खूप घाबरले होते. या योजनेने आम्ही दोघेही जगू आणि निरोगी राहू याची खात्री केली.",
    tags: ["health", "woman", "pregnancy", "mother", "child"],
    language: "multilingual",
    likes: 103,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Dnyaneshwar",
    heroNameHi: "ज्ञानेश्वर",
    heroNameMr: "ज्ञानेश्वर",
    heroAge: 55,
    heroGender: "male",
    heroOccupation: "laborer",
    heroOccupationHi: "मजदूर",
    heroOccupationMr: "मजूर",
    village: "Hingoli",
    villageHi: "हिंगोली",
    villageMr: "हिंगोली",
    district: "Hingoli",
    category: "health",
    problem: "He had a hernia for 2 years but couldn't afford surgery. The pain made it impossible to work.",
    problemHi: "उन्हें 2 साल से हर्निया था लेकिन सर्जरी नहीं करा सकते थे। दर्द के कारण काम करना असंभव हो गया था।",
    problemMr: "त्याला 2 वर्षांपासून हर्निया होता पण शस्त्रक्रिया करू शकत नव्हता. वेदनेमुळे काम करणे अशक्य झाले होते.",
    action: "He went to a health camp organized by the district hospital. They enrolled him in the Rashtriya Arogya Nidhi.",
    actionHi: "वह जिला अस्पताल द्वारा आयोजित स्वास्थ्य शिविर में गए। उन्होंने उन्हें राष्ट्रीय आरोग्य निधि में नामांकित किया।",
    actionMr: "तो जिल्हा रुग्णालयातर्फे आयोजित आरोग्य शिबिरात गेला. त्यांनी त्याला राष्ट्रीय आरोग्य निधीमध्ये नोंदणी केली.",
    result: "Free surgery at government hospital. Now he's pain-free and working regularly. His children are back in school.",
    resultHi: "सरकारी अस्पताल में मुफ्त सर्जरी। अब वह दर्द-मुक्त हैं और नियमित रूप से काम कर रहे हैं। उनके बच्चे वापस स्कूल जा रहे हैं।",
    resultMr: "शासकीय रुग्णालयात मोफत शस्त्रक्रिया. आता तो वेदनामुक्त आहे आणि नियमितपणे काम करतो आहे. त्याची मुले पुन्हा शाळेत जात आहेत.",
    message: "I thought I would die poor and in pain. This scheme proved that healthcare is a right, not a privilege.",
    messageHi: "मैंने सोचा था कि मैं गरीब और दर्द में मर जाऊंगा। इस योजना ने साबित किया कि स्वास्थ्य सेवा अधिकार है, विशेषाधिकार नहीं।",
    messageMr: "मी विचार केले की मी गरीब आणि वेदनेत मरेन. या योजनेने सिद्ध केले की आरोग्य सेवा हक्क आहे, विशेषाधिकार नाही.",
    tags: ["health", "male", "laborer", "surgery", "free"],
    language: "multilingual",
    likes: 79,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Tarabai",
    heroNameHi: "ताराबाई",
    heroNameMr: "ताराबाई",
    heroAge: 70,
    heroGender: "female",
    heroOccupation: "widow",
    heroOccupationHi: "विधवा",
    heroOccupationMr: "विधवा",
    village: "Jalgaon",
    villageHi: "जलगांव",
    villageMr: "जळगाव",
    district: "Jalgaon",
    category: "health",
    problem: "She had cataracts in both eyes and was almost blind. Her son is also poor and couldn't afford surgery.",
    problemHi: "उनकी दोनों आंखों में मोतियाबिंद था और वह लगभग अंधी थीं। उनका बेटा भी गरीब है और सर्जरी नहीं करा सकता था।",
    problemMr: "तिच्या दोन्ही डोळ्यांना मोतीबिंदू होता आणि ती जवळजवळ आंधळी होती. तिचा मुलगा देखील गरीब आहे आणि शस्त्रक्रिया करू शकत नव्हता.",
    action: "A mobile health van came to her village under the National Programme for Control of Blindness. They screened her and scheduled surgery.",
    actionHi: "राष्ट्रीय अंधत्व नियंत्रण कार्यक्रम के तहत एक मोबाइल स्वास्थ्य वैन उनके गांव आई। उन्होंने उनकी जांच की और सर्जरी निर्धारित की।",
    actionMr: "राष्ट्रीय अंधत्व नियंत्रण कार्यक्रमाअंतर्गत एक मोबाइल आरोग्य व्हॅन तिच्या गावी आली. त्यांनी तिची तपासणी केली आणि शस्त्रक्रिया निश्चित केली.",
    result: "Free cataract surgery restored her vision. Now she can see her grandchildren's faces and even does household chores.",
    resultHi: "मुफ्त मोतियाबिंद सर्जरी से उनकी दृष्टि वापस आ गई। अब वह अपने पोते-पोतियों के चेहरे देख सकती हैं और घर के काम भी करती हैं।",
    resultMr: "मोफत मोतीबिंदू शस्त्रक्रियेने तिची दृष्टी परत आली. आता ती तिच्या नातवंडांचे चेहरे पाहू शकते आणि घरकामही करते.",
    message: "I had forgotten what colors looked like. Now the world is beautiful again. Thank you, government.",
    messageHi: "मैं भूल गई थी कि रंग कैसे दिखते हैं। अब दुनिया फिर से खूबसूरत है। धन्यवाद, सरकार।",
    messageMr: "मी विसरले होते की रंग कसे दिसतात. आता जग पुन्हा सुंदर आहे. धन्यवाद, सरकार.",
    tags: ["health", "senior", "woman", "blindness", "surgery", "widow"],
    language: "multilingual",
    likes: 98,
    usedCount: 0,
    isActive: true
  },

  // ============ WIDOW STORIES (5) ============
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Gangubai",
    heroNameHi: "गंगूबाई",
    heroNameMr: "गंगूबाई",
    heroAge: 45,
    heroGender: "female",
    heroOccupation: "widow",
    heroOccupationHi: "विधवा",
    heroOccupationMr: "विधवा",
    village: "Solapur",
    villageHi: "सोलापुर",
    villageMr: "सोलापूर",
    district: "Solapur",
    category: "widow",
    problem: "Her husband died 3 years ago. She has two children and struggled to make ends meet by working as a laborer.",
    problemHi: "उनके पति की 3 साल पहले मृत्यु हो गई। उनके दो बच्चे हैं और वह मजदूरी करके गुजारा करने के लिए संघर्ष कर रही थीं।",
    problemMr: "तिचे पती 3 वर्षांपूर्वी वारले. तिला दोन मुले आहेत आणि ती मजुरी करून उदरनिर्वाह करण्यासाठी संघर्ष करत होती.",
    action: "She heard about the Sanjay Gandhi Niradhar Yojana from the Anganwadi worker. She applied for widow pension.",
    actionHi: "उन्होंने आंगनवाड़ी कार्यकर्ता से संजय गांधी निराधार योजना के बारे में सुना। उन्होंने विधवा पेंशन के लिए आवेदन किया।",
    actionMr: "तिने अंगणवाडी सेविकेकडून संजय गांधी निराधार योजनेबद्दल ऐकले. तिने विधवा पेन्शनसाठी अर्ज केला.",
    result: "She gets ₹900 per month pension. With this, she started a small papad making business at home.",
    resultHi: "उन्हें प्रति माह ₹900 पेंशन मिलती है। इससे उन्होंने घर पर छोटा पापड़ बनाने का व्यवसाय शुरू किया।",
    resultMr: "तिला दर महिन्याला ₹900 पेन्शन मिळते. यातून तिने घरच्या घरी छोटा पापड बनवण्याचा व्यवसाय सुरू केला.",
    message: "This pension gave me the courage to stand on my own feet. Now my children don't go hungry.",
    messageHi: "इस पेंशन ने मुझे अपने पैरों पर खड़े होने का साहस दिया। अब मेरे बच्चे भूखे नहीं सोते।",
    messageMr: "या पेन्शनने मला स्वतःच्या पायावर उभे राहण्याचे धैर्य दिले. आता माझी मुले भुकेली झोपत नाहीत.",
    tags: ["widow", "woman", "pension", "self-help", "business"],
    language: "multilingual",
    likes: 105,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Shantabai",
    heroNameHi: "शांताबाई",
    heroNameMr: "शांताबाई",
    heroAge: 52,
    heroGender: "female",
    heroOccupation: "widow",
    heroOccupationHi: "विधवा",
    heroOccupationMr: "विधवा",
    village: "Dhule",
    villageHi: "धुळे",
    villageMr: "धुळे",
    district: "Dhule",
    category: "widow",
    problem: "After her husband's death, her in-laws threw her out of the house. She had no place to live.",
    problemHi: "पति की मृत्यु के बाद, उसके ससुराल वालों ने उसे घर से निकाल दिया। उसके पास रहने की जगह नहीं थी।",
    problemMr: "पतीच्या मृत्यूनंतर, तिच्या सासरच्या लोकांनी तिला घरातून हाकलून दिले. तिच्याकडे राहायला जागा नव्हती.",
    action: "She applied for the Pradhan Mantri Awas Yojana (rural) through the gram panchayat.",
    actionHi: "उसने ग्राम पंचायत के माध्यम से प्रधानमंत्री आवास योजना (ग्रामीण) के लिए आवेदन किया।",
    actionMr: "तिने ग्रामपंचायतीमार्फत प्रधानमंत्री आवास योजना (ग्रामीण) साठी अर्ज केला.",
    result: "She got a house of her own under the scheme. Now she lives with dignity and also gets widow pension.",
    resultHi: "उसे योजना के तहत अपना खुद का घर मिला। अब वह गरिमा के साथ रहती है और उसे विधवा पेंशन भी मिलती है।",
    resultMr: "तिला योजनेअंतर्गत स्वतःचे घर मिळाले. आता ती प्रतिष्ठेने राहते आहे आणि तिला विधवा पेन्शनही मिळते.",
    message: "When you have your own home, you have your own identity. I'm no longer a burden to anyone.",
    messageHi: "जब आपका अपना घर होता है, तो आपकी अपनी पहचान होती है। मैं अब किसी के लिए बोझ नहीं हूं।",
    messageMr: "जेव्हा तुमचे स्वतःचे घर असते, तेव्हा तुमची स्वतःची ओळख असते. मी आता कोणावरही ओझे नाही.",
    tags: ["widow", "woman", "housing", "awas", "pension"],
    language: "multilingual",
    likes: 83,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Mangala",
    heroNameHi: "मंगला",
    heroNameMr: "मंगला",
    heroAge: 38,
    heroGender: "female",
    heroOccupation: "widow",
    heroOccupationHi: "विधवा",
    heroOccupationMr: "विधवा",
    village: "Nashik",
    villageHi: "नासिक",
    villageMr: "नाशिक",
    district: "Nashik",
    category: "widow",
    problem: "Her husband died of COVID. She had three children and no source of income.",
    problemHi: "उनके पति की COVID से मृत्यु हो गई। उनके तीन बच्चे थे और आय का कोई स्रोत नहीं था।",
    problemMr: "तिचे पती कोविडने वारले. तिला तीन मुले होती आणि उत्पन्नाचे कोणतेही साधन नव्हते.",
    action: "She received assistance under the Pradhan Mantri Garib Kalyan Yojana during COVID.",
    actionHi: "उन्हें COVID के दौरान प्रधानमंत्री गरीब कल्याण योजना के तहत सहायता मिली।",
    actionMr: "तिला कोविड दरम्यान प्रधानमंत्री गरीब कल्याण योजनेअंतर्गत मदत मिळाली.",
    result: "She got free ration and ₹500 per month for 3 months. Now she's part of a self-help group making snacks.",
    resultHi: "उन्हें 3 महीने तक मुफ्त राशन और ₹500 प्रति माह मिला। अब वह एक स्वयं सहायता समूह का हिस्सा हैं जो नाश्ता बनाती है।",
    resultMr: "तिला 3 महिने मोफत रेशन आणि दर महिन्याला ₹500 मिळाले. आता ती स्नॅक्स बनवणाऱ्या स्वयंसहायता गटाचा भाग आहे.",
    message: "When my husband died, I thought my children would starve. This scheme kept us alive.",
    messageHi: "जब मेरे पति की मृत्यु हुई, तो मुझे लगा कि मेरे बच्चे भूखे मरेंगे। इस योजना ने हमें जीवित रखा।",
    messageMr: "माझे पती वारले तेव्हा मला वाटले की माझी मुले उपाशी मरतील. या योजनेने आम्हाला जिवंत ठेवले.",
    tags: ["widow", "woman", "covid", "ration", "self-help"],
    language: "multilingual",
    likes: 91,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Sakhubai",
    heroNameHi: "सखूबाई",
    heroNameMr: "सखूबाई",
    heroAge: 60,
    heroGender: "female",
    heroOccupation: "widow",
    heroOccupationHi: "विधवा",
    heroOccupationMr: "विधवा",
    village: "Ahmednagar",
    villageHi: "अहमदनगर",
    villageMr: "अहमदनगर",
    district: "Ahmednagar",
    category: "widow",
    problem: "She had no identification documents, so she couldn't apply for any scheme. She survived by begging.",
    problemHi: "उनके पास कोई पहचान दस्तावेज नहीं थे, इसलिए वह किसी भी योजना के लिए आवेदन नहीं कर सकती थीं। वह भीख मांगकर गुजारा करती थीं।",
    problemMr: "तिच्याकडे कोणतेही ओळख दस्तऐवज नव्हते, म्हणून ती कोणत्याही योजनेसाठी अर्ज करू शकत नव्हती. ती भीक मागून उदरनिर्वाह करत होती.",
    action: "A social worker helped her get an Aadhaar card and ration card through a special camp.",
    actionHi: "एक समाजसेविका ने एक विशेष शिविर के माध्यम से उन्हें आधार कार्ड और राशन कार्ड दिलाने में मदद की।",
    actionMr: "एका समाजसेविकेने एका विशेष शिबिराद्वारे तिला आधार कार्ड आणि रेशन कार्ड मिळवून दिले.",
    result: "She now gets old age pension of ₹900 per month and free ration. She stopped begging.",
    resultHi: "उन्हें अब प्रति माह ₹900 वृद्धावस्था पेंशन और मुफ्त राशन मिलता है। उन्होंने भीख मांगना बंद कर दिया।",
    resultMr: "तिला आता दर महिन्याला ₹900 वृद्धापकाळ पेन्शन आणि मोफत रेशन मिळते. तिने भीक मागणे बंद केले.",
    message: "I never thought I would live to see this day. I have my own identity now.",
    messageHi: "मैंने कभी नहीं सोचा था कि मैं यह दिन देखने के लिए जीवित रहूंगी। अब मेरी अपनी पहचान है।",
    messageMr: "मी कधी विचार केला नव्हता की मी हा दिवस पाहण्यासाठी जगेन. आता माझी स्वतःची ओळख आहे.",
    tags: ["widow", "senior", "woman", "pension", "aadhaar"],
    language: "multilingual",
    likes: 77,
    usedCount: 0,
    isActive: true
  },
  {
    schemeId: "698489fd9d1ab3c375753564",
    heroName: "Asha",
    heroNameHi: "आशा",
    heroNameMr: "आशा",
    heroAge: 35,
    heroGender: "female",
    heroOccupation: "widow",
    heroOccupationHi: "विधवा",
    heroOccupationMr: "विधवा",
    village: "Kolhapur",
    villageHi: "कोल्हापुर",
    villageMr: "कोल्हापूर",
    district: "Kolhapur",
    category: "widow",
    problem: "Her husband was an alcoholic and left her with no savings. She had a 5-year-old daughter to raise alone.",
    problemHi: "उनके पति शराबी थे और उन्हें बिना बचत के छोड़ दिया। उन्हें अकेले 5 साल की बेटी को पालना था।",
    problemMr: "तिचे पती दारूडे होते आणि त्यांना बचत न करता सोडून गेले. तिला एकटीने 5 वर्षांच्या मुलीचे संगोपन करायचे होते.",
    action: "She enrolled in a skill development program under the National Urban Livelihoods Mission.",
    actionHi: "उन्होंने राष्ट्रीय शहरी आजीविका मिशन के तहत एक कौशल्य विकास कार्यक्रम में दाखिला लिया।",
    actionMr: "तिने राष्ट्रीय शहरी उपजीविका अभियानांतर्गत कौशल्य विकास कार्यक्रमात प्रवेश घेतला.",
    result: "She learned tailoring and got a sewing machine subsidy. Now she stitches clothes and earns ₹5,000 per month.",
    resultHi: "उन्होंने सिलाई सीखी और सिलाई मशीन सब्सिडी प्राप्त की। अब वह कपड़े सिलती हैं और प्रति माह ₹5,000 कमाती हैं।",
    resultMr: "तिने शिवणकाम शिकले आणि शिवणकाम मशीन सबसिडी मिळाली. आता ती कपडे शिवते आणि दर महिन्याला ₹5,000 कमावते.",
    message: "I was dependent on others. Now my daughter calls me her hero. That's everything to me.",
    messageHi: "मैं दूसरों पर निर्भर थी। अब मेरी बेटी मुझे अपना हीरो कहती है। यही मेरे लिए सब कुछ है।",
    messageMr: "मी इतरांवर अवलंबून होते. आता माझी मुलगी मला तिचा हिरो म्हणते. हेच माझ्यासाठी सर्व काही आहे.",
    tags: ["widow", "woman", "skill", "training", "livelihood"],
    language: "multilingual",
    likes: 112,
    usedCount: 0,
    isActive: true
  }
];

const seedStories = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    await mongoose.connection.db.collection('stories').deleteMany({});
    console.log('✅ Cleared existing stories');

    await mongoose.connection.db.collection('stories').insertMany(stories);
    console.log(`✅ Inserted ${stories.length} multilingual stories`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding stories:', error);
    process.exit(1);
  }
};

seedStories();